# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word_count.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='word_count.proto',
  package='wordcount',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10word_count.proto\x12\twordcount\"\xe0\x01\n\x04Task\x12&\n\ttask_type\x18\x01 \x01(\x0e\x32\x13.wordcount.TaskType\x12\x13\n\x0btask_number\x18\x02 \x01(\x05\x12\x18\n\x10number_map_tasks\x18\x03 \x01(\x05\x12\x1b\n\x13number_reduce_tasks\x18\x04 \x01(\x05\x12\x32\n\nbucket_ref\x18\x05 \x03(\x0b\x32\x1e.wordcount.Task.BucketRefEntry\x1a\x30\n\x0e\x42ucketRefEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\x0bTaskRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11\x61vailable_buckets\x18\x02 \x03(\t\">\n\x0cTaskResponse\x12\x1d\n\x04task\x18\x01 \x01(\x0b\x32\x0f.wordcount.Task\x12\x0f\n\x07message\x18\x02 \x01(\t*)\n\x08TaskType\x12\x07\n\x03map\x10\x00\x12\n\n\x06reduce\x10\x01\x12\x08\n\x04\x64one\x10\x02\x32I\n\tWordCount\x12<\n\x07GetTask\x12\x16.wordcount.TaskRequest\x1a\x17.wordcount.TaskResponse\"\x00\x62\x06proto3'
)

_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='wordcount.TaskType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='map', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='reduce', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='done', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=381,
  serialized_end=422,
)
_sym_db.RegisterEnumDescriptor(_TASKTYPE)

TaskType = enum_type_wrapper.EnumTypeWrapper(_TASKTYPE)
map = 0
reduce = 1
done = 2



_TASK_BUCKETREFENTRY = _descriptor.Descriptor(
  name='BucketRefEntry',
  full_name='wordcount.Task.BucketRefEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wordcount.Task.BucketRefEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='wordcount.Task.BucketRefEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=256,
)

_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='wordcount.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_type', full_name='wordcount.Task.task_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_number', full_name='wordcount.Task.task_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_map_tasks', full_name='wordcount.Task.number_map_tasks', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_reduce_tasks', full_name='wordcount.Task.number_reduce_tasks', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket_ref', full_name='wordcount.Task.bucket_ref', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TASK_BUCKETREFENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=256,
)


_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='wordcount.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='wordcount.TaskRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available_buckets', full_name='wordcount.TaskRequest.available_buckets', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=315,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='wordcount.TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='wordcount.TaskResponse.task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='wordcount.TaskResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=379,
)

_TASK_BUCKETREFENTRY.containing_type = _TASK
_TASK.fields_by_name['task_type'].enum_type = _TASKTYPE
_TASK.fields_by_name['bucket_ref'].message_type = _TASK_BUCKETREFENTRY
_TASKRESPONSE.fields_by_name['task'].message_type = _TASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.enum_types_by_name['TaskType'] = _TASKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {

  'BucketRefEntry' : _reflection.GeneratedProtocolMessageType('BucketRefEntry', (_message.Message,), {
    'DESCRIPTOR' : _TASK_BUCKETREFENTRY,
    '__module__' : 'word_count_pb2'
    # @@protoc_insertion_point(class_scope:wordcount.Task.BucketRefEntry)
    })
  ,
  'DESCRIPTOR' : _TASK,
  '__module__' : 'word_count_pb2'
  # @@protoc_insertion_point(class_scope:wordcount.Task)
  })
_sym_db.RegisterMessage(Task)
_sym_db.RegisterMessage(Task.BucketRefEntry)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'word_count_pb2'
  # @@protoc_insertion_point(class_scope:wordcount.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'word_count_pb2'
  # @@protoc_insertion_point(class_scope:wordcount.TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)


_TASK_BUCKETREFENTRY._options = None

_WORDCOUNT = _descriptor.ServiceDescriptor(
  name='WordCount',
  full_name='wordcount.WordCount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=424,
  serialized_end=497,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='wordcount.WordCount.GetTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORDCOUNT)

DESCRIPTOR.services_by_name['WordCount'] = _WORDCOUNT

# @@protoc_insertion_point(module_scope)
